# Generated by Django 4.1.4 on 2025-05-08 18:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import tests.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=255, unique=True, verbose_name='Наименование теста')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('test_image', models.ImageField(upload_to='photos/tests', verbose_name='Фото теста')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Дата изменений')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
            },
        ),
        migrations.CreateModel(
            name='TestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='start time')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='end time')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('expired', 'Expired')], default='in_progress', max_length=20)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Canditate')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.test')),
            ],
            options={
                'verbose_name': 'Test Session',
                'verbose_name_plural': 'Test Sessions',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('O', 'Openness'), ('C', 'Conscientiousness'), ('E', 'Extraversion'), ('A', 'Agreeableness'), ('N', 'Neuroticism')], max_length=1, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('low_range', models.TextField(blank=True, help_text='Description for scores 0-40%')),
                ('mid_range', models.TextField(blank=True, help_text='Description for scores 40-60%')),
                ('high_range', models.TextField(blank=True, help_text='Description for scores 60-100%')),
                ('reverse_scored', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Personality Trait',
                'verbose_name_plural': 'Personality Traits',
            },
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_scores', models.JSONField(blank=True, default=dict, null=True)),
                ('normalized_scores', models.JSONField(blank=True, default=dict)),
                ('interpretation', models.JSONField(blank=True, default=dict)),
                ('general_description', models.JSONField(blank=True, default=dict)),
                ('recommendations', models.JSONField(blank=True, default=dict)),
                ('theoretical_scores', models.JSONField(blank=True, default=dict)),
                ('scenario_analysis', models.JSONField(default=dict)),
                ('scale_evaluations', models.JSONField(default=dict)),
                ('free_response_analysis', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('correct_answer_count', models.IntegerField(verbose_name='Кол-во верных ответов')),
                ('wrong_answer_count', models.IntegerField(verbose_name='Кол-во неверных ответов')),
                ('correct_answer_percent', models.CharField(max_length=10, null=True, verbose_name='Процент правильных ответов')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата прохождения теста')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата повторного прохождения теста')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category', verbose_name='Категория')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tests.testsession')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.test', verbose_name='Тест')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Результат',
                'verbose_name_plural': 'Результаты',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('order', models.PositiveBigIntegerField(default=0)),
                ('key', models.CharField(choices=[('+', 'Positive'), ('-', 'Negative')], default='+', max_length=1)),
                ('weight', models.FloatField(blank=True, default=1.0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('question_type', models.CharField(blank=True, choices=[('yes_no', 'YES/NO'), ('multiple_choice', 'Multiple Choice'), ('open_text', 'Open Text'), ('rating_scale', '1-10 Rating Scale')], default='yes_no', max_length=50, null=True)),
                ('scale_min', models.IntegerField(blank=True, default=1, null=True, verbose_name='Նվազագույն բալ')),
                ('scale_max', models.IntegerField(blank=True, default=10, null=True, verbose_name='Մաքսիմալ բալ')),
                ('multiple_choices', models.JSONField(blank=True, help_text="Օրինակ՝ [{'text': 'Տարբերակ 1', 'value': 1}]", null=True, validators=[tests.validators.validate_options])),
                ('open_text_prompt', models.TextField(blank=True, help_text='Մուտքագրեք հարցի հրահանգները', null=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tests.test', verbose_name='Наименование теста')),
                ('trait', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='tests.trait')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=200, verbose_name='Ответ')),
                ('answer_image', models.ImageField(default='default.jpg', upload_to='photos/answers', verbose_name='Фото ответа')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Верно')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='Value')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.question', verbose_name='Question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='tests.testsession', verbose_name='Session')),
            ],
            options={
                'verbose_name': 'User Response',
                'verbose_name_plural': 'User Responses',
                'unique_together': {('session', 'question')},
            },
        ),
    ]
