# Generated by Django 4.1.4 on 2025-05-06 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='description',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='test_date',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='value',
        ),
    ]
