# Generated by Django 4.1.4 on 2025-05-06 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_remove_answer_description_remove_answer_test_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(blank=True, choices=[('yes_no', 'YES/NO'), ('multiple_choice', 'Multiple Choice'), ('open_text', 'Open Text'), ('rating_scale', '1-10 Rating Scale')], default='yes_no', max_length=50, null=True),
        ),
    ]
