# Generated by Django 4.1.4 on 2025-05-12 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_options_alter_category_category_image_and_more'),
        ('tests', '0002_alter_testsession_candidate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Պատասխան', 'verbose_name_plural': 'Պատասխաններ'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'Թեստ', 'verbose_name_plural': 'Թեստեր'},
        ),
        migrations.AlterModelOptions(
            name='trait',
            options={'verbose_name': 'Բնավորության գիծ', 'verbose_name_plural': 'Բնավորության գծեր'},
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(max_length=200, verbose_name='Պատասխան'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_image',
            field=models.ImageField(default='default.jpg', upload_to='photos/answers', verbose_name='Պատասխանի նկար'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='Պատասխանն ճիշտ է'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.question', verbose_name='Հարց'),
        ),
        migrations.AlterField(
            model_name='question',
            name='key',
            field=models.CharField(choices=[('+', 'Positive'), ('-', 'Negative')], default='+', max_length=1, verbose_name='Հարցի բանալին +/-'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(verbose_name='Հարց'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(blank=True, choices=[('yes_no', 'YES/NO'), ('multiple_choice', 'Multiple Choice'), ('open_text', 'Open Text'), ('rating_scale', '1-10 Rating Scale')], default='yes_no', max_length=50, null=True, verbose_name='Հարցի տեսակ'),
        ),
        migrations.AlterField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tests.test', verbose_name='Թեստի անվանում'),
        ),
        migrations.AlterField(
            model_name='question',
            name='trait',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='tests.trait', verbose_name='Բնավորության գիծ'),
        ),
        migrations.AlterField(
            model_name='test',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category', verbose_name='Թեստի կատեգորիա'),
        ),
        migrations.AlterField(
            model_name='test',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ստեղծման ամսաթիվ'),
        ),
        migrations.AlterField(
            model_name='test',
            name='description',
            field=models.TextField(blank=True, verbose_name='Թեստի նկարագրություն'),
        ),
        migrations.AlterField(
            model_name='test',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Փոփոխման ամսաթիվ'),
        ),
        migrations.AlterField(
            model_name='test',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Թեստի URL հղման համար'),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_image',
            field=models.ImageField(upload_to='photos/tests', verbose_name='Թեստի նկար'),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Թեստի անվանում'),
        ),
        migrations.AlterField(
            model_name='trait',
            name='code',
            field=models.CharField(choices=[('O', 'Լայնախոհություն'), ('C', 'Բարեխղճություն'), ('E', 'Էքստրավերտություն'), ('A', 'Բարյացակամություն'), ('N', 'Նեյրոտիզմ')], max_length=1, unique=True, verbose_name='Կոդ'),
        ),
        migrations.AlterField(
            model_name='trait',
            name='description',
            field=models.TextField(verbose_name='Նկարագրություն'),
        ),
        migrations.AlterField(
            model_name='trait',
            name='high_range',
            field=models.TextField(blank=True, help_text='Description for scores 60-100%', verbose_name='Բարձր միջակայք'),
        ),
        migrations.AlterField(
            model_name='trait',
            name='low_range',
            field=models.TextField(blank=True, help_text='Description for scores 0-40%', verbose_name='Ցածր միջակայք'),
        ),
        migrations.AlterField(
            model_name='trait',
            name='mid_range',
            field=models.TextField(blank=True, help_text='Description for scores 40-60%', verbose_name='Միջին միջակայք'),
        ),
        migrations.AlterField(
            model_name='trait',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Անվանում'),
        ),
    ]
