# Generated by Django 4.1.4 on 2025-05-07 22:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tests', '0003_alter_question_question_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='Արժեք')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ստեղծման ամսաթիվ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.question', verbose_name='Հարց')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Օգտագործող')),
            ],
            options={
                'verbose_name': 'Օգտագործողի պատասխան',
                'verbose_name_plural': 'Օգտագործողների պատասխաններ',
                'unique_together': {('user', 'question')},
            },
        ),
    ]
